# Generated by Django 5.0.4 on 2024-05-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
